version: "3.8"
# postgres service

services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_crud
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data


